/**
 * Plain-language meaning for an ontology value: what the theme is, and how it
 * tends to show up in a life. Used by the convergence chart's Quick info panel.
 * Original prose, deterministic, read-only. Keyed by axis then bare value (the
 * part after any "family:" namespace), so western:fire and chinese:fire share the
 * fire read while staying distinct values in the synthesis.
 */
import type { OntologyAxis } from "@/lib/core/contracts";

export interface ValueMeaning {
  essence: string;
  life: string;
  strength: string;
  growthEdge: string;
}

const ELEMENT: Record<string, ValueMeaning> = {
  fire: { essence: "Drive, warmth, and the urge to begin", life: "When fire runs strong you initiate, inspire, and move first. In life it shows up as enthusiasm and momentum. The work is to channel the spark so it warms rather than burns out.", strength: "You bring energy that gets things moving, and people catch your spark and want to follow.", growthEdge: "Consider where a steadier pace could let your fire warm a project the whole way through." },
  earth: { essence: "Groundedness, patience, and the tangible", life: "Earth makes you build, steady, and tend what is real. In life it shows up as reliability and follow-through. The work is to stay solid without becoming stuck.", strength: "You are the one others trust to follow through, and you build things that genuinely last.", growthEdge: "You might explore where a little flexibility opens room for change you would actually enjoy." },
  air: { essence: "Mind, connection, and exchange", life: "Air has you thinking, talking, and linking ideas and people. In life it shows up as curiosity and social ease. The work is to land your ideas, not only circulate them.", strength: "Your quick mind connects ideas and people in ways that spark fresh thinking everywhere you go.", growthEdge: "Try landing one idea fully into action, and notice how good it feels to finish." },
  water: { essence: "Feeling, depth, and flow", life: "Water has you sensing undercurrents and moving around obstacles. In life it shows up as empathy and intuition. The work is to feel fully without being swept away.", strength: "You feel what others miss, and your empathy helps people feel deeply understood and safe.", growthEdge: "You could practice a gentle boundary that lets you feel fully while staying anchored in yourself." },
  wood: { essence: "Upward growth and vision", life: "Wood has you planning, expanding, and pushing toward the light. In life it shows up as ambition and benevolence. The work is to bend without breaking.", strength: "You grow toward what matters with real vision, and your ambition lifts the people around you.", growthEdge: "Notice where bending a little, instead of pushing harder, helps you reach the light you want." },
  metal: { essence: "Clarity, structure, and refinement", life: "Metal has you cutting to what matters and holding standards. In life it shows up as discernment and poise. The work is to stay precise without going rigid.", strength: "Your clarity cuts straight to what matters, and your standards make everything you touch finer.", growthEdge: "Consider letting a little softness in, so your precision has room to breathe and adapt." },
};

const POLARITY: Record<string, ValueMeaning> = {
  active: { essence: "An outward, initiating current", life: "You tend to move first, push, and make things happen. In life it shows up as initiative and visible energy. It is balanced by knowing when to wait.", strength: "You make things happen, and your willingness to move first opens doors for everyone around you.", growthEdge: "You might explore the quiet power of waiting, and let the right moment come to meet you." },
  receptive: { essence: "An inward, attuning current", life: "You tend to receive, respond, and read the moment. In life it shows up as patience and sensitivity to timing. It is balanced by knowing when to move.", strength: "You read the moment beautifully, and your patience lets the right opportunities find their way to you.", growthEdge: "Consider where moving first, before you feel fully ready, could bring something you genuinely want." },
  balanced: { essence: "Both push and pause", life: "You carry both currents, so your real task is timing: when to act, and when to let things come to you.", strength: "You hold both action and stillness, and you can shift between them as each moment calls for.", growthEdge: "You could keep tuning your timing, trusting that you already know when to push and when to pause." },
};

const THEME: Record<string, ValueMeaning> = {
  leadership: { essence: "A pull to direct and take responsibility", life: "You set direction and carry the weight others lean on. In life it shows up as people looking to you to decide. The growth is to lead without needing to control.", strength: "People look to you to set the course, and you carry that responsibility with real steadiness.", growthEdge: "You might explore leading by trust, and let others own their part of the work too." },
  communication: { essence: "Words, ideas, and exchange", life: "You connect through what you say and hear. In life it shows up as a knack for explaining, linking, and persuading. The growth is to listen as much as you speak.", strength: "You have a gift for words, and you help people understand each other and feel truly heard.", growthEdge: "Try leaving extra space to listen, and notice what you learn when you speak less." },
  sensitivity: { essence: "Fine-tuned receptivity to feeling", life: "You pick up moods and undercurrents others miss. In life it shows up as empathy and a need for gentle environments. The growth is a boundary so you are not flooded.", strength: "You sense what others feel before they say it, and that attunement makes people feel deeply safe.", growthEdge: "You could build a kind boundary that protects your sensitivity, so you stay open without flooding." },
  transformation: { essence: "Depth, endings, and rebirth", life: "You are changed by what you go through, and you change what you touch. In life it shows up as intensity and a refusal of the surface. The growth is to let intensity heal rather than control.", strength: "You go deep where others stay on the surface, and you help things and people truly renew.", growthEdge: "Consider letting your intensity become a healing force, trusting change instead of trying to steer it." },
  structure: { essence: "Order, form, and reliability", life: "You build frameworks that last. In life it shows up as dependability and a steady hand. The growth is to keep the structure serving you, not the reverse.", strength: "You create order that holds, and the frameworks you build give everyone around you a place to stand.", growthEdge: "You might check that your structures still serve you, and loosen the ones that have outgrown their use." },
  nurture: { essence: "Care, provision, and safety", life: "You tend and make others feel held. In life it shows up as the one who provides and protects. The growth is to include yourself in the care.", strength: "You make people feel held and safe, and your care creates a warmth others carry with them.", growthEdge: "Try turning some of that generous care toward yourself, and let your own needs count too." },
  exploration: { essence: "A reach for the new and meaningful", life: "You expand horizons and chase what matters. In life it shows up as wanderlust and big questions. The growth is to root the vision in lived detail.", strength: "Your curiosity opens new horizons, and you draw others toward questions and places that matter.", growthEdge: "You could ground one big vision in small daily details, and watch it take real shape." },
  discipline: { essence: "Focus, effort, and the long game", life: "You do the work and stay the course. In life it shows up as grit and the ability to delay reward. The growth is to let rest and play count too.", strength: "You stay the course when others drift, and your steady effort turns long goals into real results.", growthEdge: "Consider letting rest and play count as part of the work, not a break from it." },
  intuition: { essence: "A direct, non-verbal knowing", life: "You sense answers before you can explain them. In life it shows up as good hunches and reading rooms. The growth is to trust it, and to check it.", strength: "You know things before you can explain them, and your hunches guide you well again and again.", growthEdge: "You might practice trusting that inner knowing, and gently checking it against what you observe." },
  vision: { essence: "A future-facing imagination", life: "You see what could be. In life it shows up as ideas ahead of their time. The growth is to ground the vision in a first real step.", strength: "You see what could be before anyone else does, and your ideas pull the future a little closer.", growthEdge: "Try taking one real first step, and let your vision begin meeting the ground beneath it." },
  service: { essence: "A pull to be useful", life: "You help through competence and care. In life it shows up as fixing, improving, and showing up. The growth is to serve from fullness, not depletion.", strength: "You show up and make things better, and your skillful care quietly improves everything you touch.", growthEdge: "You could give from a full cup, refilling yourself first so your service stays joyful." },
  sovereignty: { essence: "Self-possession and your own authority", life: "You move under your own steam and resist being managed. In life it shows up as independence and quiet power. The growth is to stay open while standing in it.", strength: "You stand in your own authority, and that quiet independence gives you a grounded, unforced power.", growthEdge: "You might explore staying open and connected while you hold your ground, letting others in close." },
  devotion: { essence: "Deep commitment to chosen bonds", life: "You give yourself fully to people and values you choose. In life it shows up as loyalty and wholeheartedness. The growth is to choose where your loyalty lands.", strength: "You love and commit wholeheartedly, and the people you choose feel the rare gift of your loyalty.", growthEdge: "Consider choosing with care where your devotion lands, so it always meets what truly deserves it." },
  analysis: { essence: "A drive to examine and refine", life: "You see the parts and the flaws. In life it shows up as precision and useful critique. The growth is to let 'good enough' be a kind of mercy.", strength: "You see the parts clearly, and your eye for detail makes the work sharper and more trustworthy.", growthEdge: "You could let 'good enough' be a kindness sometimes, freeing your sharp eye for what matters most." },
  play: { essence: "Spontaneity, joy, and lightness", life: "You create through delight. In life it shows up as humor and a refusal to take everything heavily. The growth is to let play carry real weight.", strength: "You bring lightness and joy, and your sense of play makes hard things feel possible for everyone.", growthEdge: "You might trust that your playfulness carries real weight, and let it shape serious work too." },
};

const CENTER: Record<string, ValueMeaning> = {
  head: { essence: "Mental pressure and inspiration", life: "The urge to make sense of things and ask questions. It drives your curiosity and the problems you choose to chew on.", strength: "Your mind reaches for meaning, and the questions you ask open doors others never thought to try.", growthEdge: "You might let some questions simply rest, trusting that not every one needs an answer right now." },
  ajna: { essence: "How you process concepts", life: "Your way of thinking things through and holding ideas. It shapes how you form and defend a view.", strength: "You think things through with real care, and your way of holding ideas brings clarity to others.", growthEdge: "Consider holding your views a little more lightly, leaving room for new information to land." },
  throat: { essence: "Expression and manifestation", life: "How you speak and bring things into the world. It governs whether ideas stay inside or become action.", strength: "You give voice to what matters, and you have a real gift for turning ideas into action.", growthEdge: "You could trust the timing of your voice, speaking when the moment is genuinely ready for it." },
  g: { essence: "Identity, love, and direction", life: "Your sense of who you are and where you are headed. It steers your direction and the people you feel at home with.", strength: "You carry a clear sense of self, and that grounded identity guides you toward the right people and paths.", growthEdge: "You might let your direction unfold over time, trusting it to clarify as you keep moving." },
  heart: { essence: "Willpower and worth", life: "Drive, ego, and what you commit to. It governs the promises you make and the proving you do.", strength: "You have real willpower, and when you commit to something, people can count on you to follow through.", growthEdge: "Consider letting your worth rest in who you are, not only in what you prove or achieve." },
  sacral: { essence: "Life-force and work energy", life: "What you have the energy to sustain. It governs the work and relationships that genuinely light you up.", strength: "You have deep, renewable energy, and you pour it generously into the work and people that light you up.", growthEdge: "You might follow what genuinely energizes you, and gently set down what quietly drains you." },
  "solar-plexus": { essence: "Emotional waves", life: "Your feelings move in cycles, and clarity comes over time. It asks you to ride the wave before deciding.", strength: "You feel things in rich waves, and that emotional depth gives your choices real wisdom over time.", growthEdge: "You could give big decisions time, letting clarity arrive naturally as the wave settles within you." },
  spleen: { essence: "Instinct and well-being", life: "In-the-moment intuition and a sense of safety. It is the quiet voice that keeps you well.", strength: "Your instincts are quick and true, and that quiet inner voice keeps you well and safe.", growthEdge: "You might practice trusting your first quiet hunch, even when it speaks just once and softly." },
  root: { essence: "Pressure and drive", life: "The adrenalized push to get things done. It fuels your momentum and, unmanaged, your stress.", strength: "You carry real drive, and that pressure fuels the momentum to get meaningful things done.", growthEdge: "Consider choosing which pressures you take on, so your drive energizes you instead of wearing you down." },
};

const DOMAIN: Record<string, ValueMeaning> = {
  self: { essence: "Identity and how you show up", life: "This colors your whole approach to life and the first impression you make.", strength: "You have a presence that is unmistakably yours, and people feel it the moment you walk in.", growthEdge: "You might let how you show up keep evolving, trusting there is always more of you to meet." },
  resources: { essence: "Money, values, and security", life: "Where you build stability and what you treat as worth having.", strength: "You know how to build real stability, and you have a clear sense of what is worth having.", growthEdge: "Consider letting your sense of security come from within too, not only from what you can hold." },
  communication: { essence: "Learning and daily exchange", life: "How you think, speak, and move through everyday connections.", strength: "You stay curious and connected, and your everyday exchanges keep your mind alive and growing.", growthEdge: "You could slow some conversations down, giving the deeper ones room to fully unfold." },
  home: { essence: "Roots, family, and belonging", life: "Where you come from and what makes you feel safe and held.", strength: "You carry a deep sense of belonging, and you know how to make a place feel safe and warm.", growthEdge: "You might explore making home wherever you are, carrying that sense of safety inside you." },
  creativity: { essence: "Play, romance, and expression", life: "How you create, flirt, and let yourself be seen for joy.", strength: "You create and express with real joy, and you let yourself be seen in ways that delight others.", growthEdge: "You could keep sharing your creations openly, trusting that being seen is part of the joy." },
  "service-health": { essence: "Work, habits, and the body", life: "The daily routines and care that keep you functioning well.", strength: "You tend to the daily details well, and your routines quietly keep you healthy and capable.", growthEdge: "You might let your habits flex when life shifts, treating your body with patience as well as care." },
  relationship: { essence: "Partnership and the one-to-one", life: "How you meet another as an equal, and what you seek in a partner.", strength: "You meet others as equals, and you bring honesty and presence to your closest one-to-one bonds.", growthEdge: "Consider staying fully yourself within partnership, letting closeness add to who you are." },
  transformation: { essence: "Intimacy, shared resources, and change", life: "Where you merge deeply with others and are remade by it.", strength: "You are not afraid to go deep, and real intimacy with others changes and strengthens you.", growthEdge: "You might let yourself be remade by closeness, trusting the change that deep connection brings." },
  philosophy: { essence: "Meaning, travel, and the big picture", life: "What you believe and how far you reach for understanding.", strength: "You reach for meaning and the big picture, and your search for understanding widens everyone's view.", growthEdge: "You could let your beliefs keep growing, staying open to truths you have not met yet." },
  vocation: { essence: "Career and public role", life: "How you are known in the world and what you are building toward.", strength: "You are building something the world can see, and your public role reflects what you truly value.", growthEdge: "You might let your sense of purpose lead the way, with recognition following in its own time." },
  community: { essence: "Friends, networks, and the future", life: "The people you build with and the future you aim at together.", strength: "You build with others toward a shared future, and your networks carry real warmth and purpose.", growthEdge: "You could keep choosing communities that match your hopes, investing where the vision is mutual." },
  spirituality: { essence: "The unseen, rest, and dissolution", life: "Where the boundaries of self soften, in rest, art, or the sacred.", strength: "You sense the unseen and know how to truly rest, finding renewal where the self gently softens.", growthEdge: "You might make regular space for rest and the sacred, letting yourself dissolve and return restored." },
};

const BY_AXIS: Partial<Record<OntologyAxis, Record<string, ValueMeaning>>> = {
  element: ELEMENT,
  polarity: POLARITY,
  theme: THEME,
  center: CENTER,
  domain: DOMAIN,
};

/** The meaning of an (axis, value), or null if we do not have prose for it yet. */
export function convergenceMeaning(axis: OntologyAxis, value: string): ValueMeaning | null {
  const bare = value.includes(":") ? value.split(":")[1] : value;
  return BY_AXIS[axis]?.[bare] ?? null;
}
